-- OTO OLUŞTURULMUŞ SEED DATASI
-- USERS
INSERT INTO users (id, name, email, phone, role, avatar_url) VALUES ('host_seda_hanım', 'Seda Hanım', 'host_seda_hanım@example.com', '05550000000', 'host', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150');
INSERT INTO users (id, name, email, phone, role, avatar_url) VALUES ('host_meliha_demir', 'Meliha Demir', 'host_meliha_demir@example.com', '05550000000', 'host', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150');
INSERT INTO users (id, name, email, phone, role, avatar_url) VALUES ('host_hakan_kaptan', 'Hakan Kaptan', 'host_hakan_kaptan@example.com', '05550000000', 'host', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150');
INSERT INTO users (id, name, email, phone, role, avatar_url) VALUES ('host_yavuz_akman', 'Yavuz Akman', 'host_yavuz_akman@example.com', '05550000000', 'host', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150');
INSERT INTO users (id, name, email, phone, role, avatar_url) VALUES ('host_mustafa_bey', 'Mustafa Bey', 'host_mustafa_bey@example.com', '05550000000', 'host', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150');
INSERT INTO users (id, name, email, phone, role, avatar_url) VALUES ('host_esra_hanım', 'Esra Hanım', 'host_esra_hanım@example.com', '05550000000', 'host', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150');
INSERT INTO users (id, name, email, phone, role, avatar_url) VALUES ('host_kamil_can', 'Kamil Can', 'host_kamil_can@example.com', '05550000000', 'host', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150');
INSERT INTO users (id, name, email, phone, role, avatar_url) VALUES ('host_salih_yıldırım', 'Salih Yıldırım', 'host_salih_yıldırım@example.com', '05550000000', 'host', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150');
INSERT INTO users (id, name, email, phone, role, avatar_url) VALUES ('host_canan_hanım', 'Canan Hanım', 'host_canan_hanım@example.com', '05550000000', 'host', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150');
INSERT INTO users (id, name, email, phone, role, avatar_url) VALUES ('host_arzu_demir', 'Arzu Demir', 'host_arzu_demir@example.com', '05550000000', 'host', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150');
INSERT INTO users (id, name, email, phone, role, avatar_url) VALUES ('host_ömer_kaya', 'Ömer Kaya', 'host_ömer_kaya@example.com', '05550000000', 'host', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150');
-- EXTRA SERVICES
INSERT INTO extra_services (id, name, price, type) VALUES ('breakfast', 'VIP Kahvaltı Servisi', 400, 'per_person_daily') ON CONFLICT DO NOTHING;
INSERT INTO extra_services (id, name, price, type) VALUES ('dinner', 'Yat Aşçısı Akşam Yemeği Menüsü', 1500, 'per_person_daily') ON CONFLICT DO NOTHING;
-- VILLAS
INSERT INTO villas (id, name, type, title, region, capacity, bedrooms, bathrooms, price_per_night, description, badge, whatsapp_message, rating, review_count, host_id, approval_status, featured_categories, min_nights, is_boat, boat_type, boat_skipper, boat_concept, boat_port) 
  VALUES ('sapanca-dome', 'Sapanca Glass Dome', 'bungalow', 'Isıtmalı Havuzlu Lüks Glamping Dome', 'Sakarya', 2, 1, 1, 5200, 'Doğa manzarasına hakim, yemyeşil özel bahçe içerisinde konumlanmış lüks cam kubbe (dome) bungalovumuz. Özel ısıtmalı havuz, jakuzi, şömine sobası ve açık hava barbekü alanı ile çiftler için rüya gibi bir balayı ve baş başa tatil imkanı sunmaktadır.', 'Popüler & Balayı', 'Merhaba! Web sitenizden Sapanca Glass Dome için bilgi/rezervasyon talep etmek istiyorum.', 4.96, 42, 'host_seda_hanım', 'approved', '[]', 2, 0, '', '', '', '');
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_sapanca-dome_0', 'sapanca-dome', 'https://images.unsplash.com/photo-1629812456605-4a044aa38fbc?auto=format&fit=crop&q=80&w=800', 'vitrin', 0);
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_sapanca-dome_1', 'sapanca-dome', 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&q=80&w=800', 'vitrin', 1);
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_sapanca-dome_2', 'sapanca-dome', 'https://images.unsplash.com/photo-1542718610-a1d656d1884c?auto=format&fit=crop&q=80&w=800', 'vitrin', 2);
INSERT INTO villas (id, name, type, title, region, capacity, bedrooms, bathrooms, price_per_night, description, badge, whatsapp_message, rating, review_count, host_id, approval_status, featured_categories, min_nights, is_boat, boat_type, boat_skipper, boat_concept, boat_port) 
  VALUES ('kirkpinar-nest', 'Kırkpınar Family Villa', 'villa', 'Geniş Aileler İçin Müstakil Havuzlu Lüks Villa', 'Sakarya', 8, 4, 3, 12500, 'Doğayla iç içe, 4 yatak odalı ve 8 kişi kapasiteli ultra lüks müstakil villa. Isıtmalı geniş yüzme havuzu, çocuk oyun alanı, geniş barbekü verandası ve tam donanımlı mutfağı ile kalabalık aileler veya arkadaş grupları için mükemmel bir korunaklı tatil seçeneğidir.', 'Lüks & Müstakil', 'Merhaba! Web sitenizden Kırkpınar Family Villa için bilgi/rezervasyon talep etmek istiyorum.', 4.88, 29, 'host_meliha_demir', 'approved', '[]', 4, 0, '', '', '', '');
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_kirkpinar-nest_0', 'kirkpinar-nest', 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800', 'vitrin', 0);
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_kirkpinar-nest_1', 'kirkpinar-nest', 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800', 'vitrin', 1);
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_kirkpinar-nest_2', 'kirkpinar-nest', 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=800', 'vitrin', 2);
INSERT INTO villas (id, name, type, title, region, capacity, bedrooms, bathrooms, price_per_night, description, badge, whatsapp_message, rating, review_count, host_id, approval_status, featured_categories, min_nights, is_boat, boat_type, boat_skipper, boat_concept, boat_port) 
  VALUES ('bosphorus-princess-cat', 'Princess Azure Katamaran', 'boat', 'Boğaz sularında Kaptanlı Ultra Lüks Katamaran Deneyimi', 'İstanbul', 12, 3, 2, 18500, 'İstanbul sularında tamamen izole bir tatil arzulayanlar için tasarlanmış, profesyonel mürettebatlı ve kaptanlı katamaran. Jakuzi, geniş kıç güverte, flybridge ve su sporları ekipmanları mevcuttur.', 'Yüzer Havuz & VIP', 'Merhaba! Web sitenizden Princess Azure Katamaran için rezervasyon sormak istiyorum.', 5, 16, 'host_hakan_kaptan', 'approved', '[]', 1, 1, 'Katamaran', 'Kaptanlı & Mürettebatlı', 'Haftalık/Günlük Özel Seyir', 'Kuruçeşme Marinası, İstanbul');
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_bosphorus-princess-cat_0', 'bosphorus-princess-cat', 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&q=80&w=800', 'vitrin', 0);
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_bosphorus-princess-cat_1', 'bosphorus-princess-cat', 'https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?auto=format&fit=crop&q=80&w=800', 'vitrin', 1);
INSERT INTO villas (id, name, type, title, region, capacity, bedrooms, bathrooms, price_per_night, description, badge, whatsapp_message, rating, review_count, host_id, approval_status, featured_categories, min_nights, is_boat, boat_type, boat_skipper, boat_concept, boat_port) 
  VALUES ('bursa-snowy-chalet', 'Uludağ Snowy Chalet', 'chalet', 'Şömineli ve Jakuzili Lüks Dağ Evi', 'Bursa', 6, 3, 2, 9500, 'Uludağ eteklerinde, bembeyaz çam ormanlarıyla çevrili rustik taş ve ahşap mimariye sahip dağ evimiz. Şömine başında sıcak çayınızı yudumlarken kış masalını yaşayabilirsiniz.', 'Kış Seçimi', 'Merhaba! Web sitenizden Uludağ Snowy Chalet için bilgi ve rezervasyon talep ediyorum.', 4.93, 22, 'host_yavuz_akman', 'approved', '[]', 2, 0, '', '', '', '');
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_bursa-snowy-chalet_0', 'bursa-snowy-chalet', 'https://images.unsplash.com/photo-1549693578-d683be217e58?auto=format&fit=crop&q=80&w=800', 'vitrin', 0);
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_bursa-snowy-chalet_1', 'bursa-snowy-chalet', 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800', 'vitrin', 1);
INSERT INTO villas (id, name, type, title, region, capacity, bedrooms, bathrooms, price_per_night, description, badge, whatsapp_message, rating, review_count, host_id, approval_status, featured_categories, min_nights, is_boat, boat_type, boat_skipper, boat_concept, boat_port) 
  VALUES ('kalkan-conservative-1', 'Villa Alesta Kalkan', 'villa', 'Muhafazakar Aileler İçin Korunaklı Özel Havuzlu Lüks Villa', 'Balıkesir', 6, 3, 3, 13900, 'Dışarıdan tamamen korunaklı, havuzu görünmeyen muhafazakar konsept lüks villamız. Akdeniz esintisiyle geniş güneşlenme alanı ve konforlu bahçesiyle ailenizle huzurlu bir izole tatil sunmaktadır.', 'Muhafazakar & Korunaklı', 'Merhaba! Web sitenizden Villa Alesta Kalkan için bilgi almak istiyorum.', 4.95, 38, 'host_mustafa_bey', 'approved', '[]', 3, 0, '', '', '', '');
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_kalkan-conservative-1_0', 'kalkan-conservative-1', 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800', 'vitrin', 0);
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_kalkan-conservative-1_1', 'kalkan-conservative-1', 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=800', 'vitrin', 1);
INSERT INTO villas (id, name, type, title, region, capacity, bedrooms, bathrooms, price_per_night, description, badge, whatsapp_message, rating, review_count, host_id, approval_status, featured_categories, min_nights, is_boat, boat_type, boat_skipper, boat_concept, boat_port) 
  VALUES ('sapanca-honeymoon-bungalow', 'Sapanca Love Bungalov', 'bungalow', 'Özel Havuzlu & Şömineli Balayı Bungalovu', 'Sakarya', 2, 1, 1, 4800, 'Yeni evli çiftlerimiz için her detayı özenle düşünülmüş, romantik balayı konsepti. Isıtmalı havuz, şömine soba ve çift kişilik jakuzi ayrıcalığıyla doğanın tam ortasında aşk dolu anlar.', 'Hemen Kiralık & Balayı', 'Merhaba! Web sitenizden Sapanca Love Bungalov için bilgi almak istiyorum.', 4.99, 54, 'host_esra_hanım', 'approved', '[]', 2, 0, '', '', '', '');
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_sapanca-honeymoon-bungalow_0', 'sapanca-honeymoon-bungalow', 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&q=80&w=800', 'vitrin', 0);
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_sapanca-honeymoon-bungalow_1', 'sapanca-honeymoon-bungalow', 'https://images.unsplash.com/photo-1542718610-a1d656d1884c?auto=format&fit=crop&q=80&w=800', 'vitrin', 1);
INSERT INTO villas (id, name, type, title, region, capacity, bedrooms, bathrooms, price_per_night, description, badge, whatsapp_message, rating, review_count, host_id, approval_status, featured_categories, min_nights, is_boat, boat_type, boat_skipper, boat_concept, boat_port) 
  VALUES ('bodrum-sunset-apartment', 'Bodrum Marina Sunset Daire', 'apartment', 'Şehir Merkezinde Deniz Manzaralı Lüks Daire', 'İstanbul', 4, 2, 1, 6500, 'Merkezi konumda, tüm sahil şeridine ve marinaya hakim harika bir teras dairesi. Modern tasarımı ile konforlu ve bağımsız bir konaklama alternatifi sunmaktadır.', 'Kentsel & Konfor', 'Merhaba! Bodrum Marina Sunset Daire için bilgi alabilir miyim?', 4.85, 19, 'host_kamil_can', 'approved', '[]', 2, 0, '', '', '', '');
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_bodrum-sunset-apartment_0', 'bodrum-sunset-apartment', 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=800', 'vitrin', 0);
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_bodrum-sunset-apartment_1', 'bodrum-sunset-apartment', 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800', 'vitrin', 1);
INSERT INTO villas (id, name, type, title, region, capacity, bedrooms, bathrooms, price_per_night, description, badge, whatsapp_message, rating, review_count, host_id, approval_status, featured_categories, min_nights, is_boat, boat_type, boat_skipper, boat_concept, boat_port) 
  VALUES ('fethiye-conservative-family', 'Villa Hilal Fethiye', 'villa', 'Muhafazakar Ailelere Özel Korunaklı Isıtmalı Havuzlu Villa', 'Sakarya', 8, 4, 4, 14500, 'Muhafazakar aile yapılarına tam uygun, her yönden kapalı gizli havuz verandası olan ultra lüks tatil villası. Bahçesinde çocuk parkı ve keyifli bir barbekü alanı barındırır. Ön onay gerektirmeyen anında rezervasyon imkanı bulunur.', 'Anında Onay & Muhafazakar', 'Merhaba! Villa Hilal Fethiye için anında onaylı kiralama detaylarını sormak istiyorum.', 4.92, 31, 'host_salih_yıldırım', 'approved', '[]', 3, 0, '', '', '', '');
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_fethiye-conservative-family_0', 'fethiye-conservative-family', 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800', 'vitrin', 0);
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_fethiye-conservative-family_1', 'fethiye-conservative-family', 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800', 'vitrin', 1);
INSERT INTO villas (id, name, type, title, region, capacity, bedrooms, bathrooms, price_per_night, description, badge, whatsapp_message, rating, review_count, host_id, approval_status, featured_categories, min_nights, is_boat, boat_type, boat_skipper, boat_concept, boat_port) 
  VALUES ('sapanca-vip-bungalow', 'Sapanca Deluxe Loft', 'bungalow', 'Ön Onay Beklemeden Anında Kiralık Jakuzili Isıtmalı Havuzlu Bungalov', 'Sakarya', 4, 2, 2, 5500, 'Beklemeksizin anında onaylanan, lüks iç mimarisi ve Isıtmalı özel cam havuz alanı ile Sapanca’nın en popüler loft tasarımlı bungalov evlerinden biri.', 'Anında Rezervasyon & Hemen', 'Merhaba! Sapanca Deluxe Loft bungalovu anında kiralamak istiyorum.', 4.97, 47, 'host_canan_hanım', 'approved', '[]', 1, 0, '', '', '', '');
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_sapanca-vip-bungalow_0', 'sapanca-vip-bungalow', 'https://images.unsplash.com/photo-1629812456605-4a044aa38fbc?auto=format&fit=crop&q=80&w=800', 'vitrin', 0);
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_sapanca-vip-bungalow_1', 'sapanca-vip-bungalow', 'https://images.unsplash.com/photo-1542718610-a1d656d1884c?auto=format&fit=crop&q=80&w=800', 'vitrin', 1);
INSERT INTO villas (id, name, type, title, region, capacity, bedrooms, bathrooms, price_per_night, description, badge, whatsapp_message, rating, review_count, host_id, approval_status, featured_categories, min_nights, is_boat, boat_type, boat_skipper, boat_concept, boat_port) 
  VALUES ('antalya-honeymoon-villa', 'Villa Swan Balayı', 'villa', 'Kalkan Koyu Manzaralı Şık Balayı Villası', 'Balıkesir', 2, 1, 1, 9800, 'Nefes kesici deniz manzarasına karşı, jakuzili, korunaklı açık sonsuzluk havuzuna sahip harika balayı villası. Balayı çiftlerine özel ikram sepeti dâhildir.', 'Anında Onay & Balayı', 'Merhaba! Villa Swan Balayı için rezervasyon sormak istiyorum.', 4.98, 23, 'host_arzu_demir', 'approved', '[]', 3, 0, '', '', '', '');
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_antalya-honeymoon-villa_0', 'antalya-honeymoon-villa', 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=800', 'vitrin', 0);
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_antalya-honeymoon-villa_1', 'antalya-honeymoon-villa', 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800', 'vitrin', 1);
INSERT INTO villas (id, name, type, title, region, capacity, bedrooms, bathrooms, price_per_night, description, badge, whatsapp_message, rating, review_count, host_id, approval_status, featured_categories, min_nights, is_boat, boat_type, boat_skipper, boat_concept, boat_port) 
  VALUES ('izole-conservative-dome', 'Korunaklı Doğa Dome', 'bungalow', 'Muhafazakar Uygun Isıtmalı Havuzlu Havuzu Görünmeyen Dome', 'Sakarya', 2, 1, 1, 5100, 'Ağaçlarla çevrelenmiş, dış gözlerden tamamen ırak dizayn edilmiş muhafazakar tasarım cam kubbe bungalov. Dışarıdan görünmeyen korunaklı sıcak havuz alanında huzurlu bir inziva.', 'Muhafazakar & Hemen Kiralık', 'Merhaba! Korunaklı Doğa Dome için sormak istiyorum.', 4.94, 15, 'host_ömer_kaya', 'approved', '[]', 2, 0, '', '', '', '');
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_izole-conservative-dome_0', 'izole-conservative-dome', 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&q=80&w=800', 'vitrin', 0);
INSERT INTO villa_images (id, villa_id, image_url, category, display_order) VALUES ('img_izole-conservative-dome_1', 'izole-conservative-dome', 'https://images.unsplash.com/photo-1629812456605-4a044aa38fbc?auto=format&fit=crop&q=80&w=800', 'vitrin', 1);